---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: NSX-T Overlay Transport Zone
      nsxt_transport_zone:
        display_name: testTZ
        description: "Ansible created TZ for Overlay Traffic"
        host_switch_name: hs1
        transport_type: 'OVERLAY'
        tags:
          nsc/cluster: k8s-cl1
        state: present
        nsx_manager: "{{ hostvars['nsx-manager'].ansible_ssh_host }}"
        nsx_username: 'admin'
        nsx_passwd: "{{ hostvars['nsx-manager'].ansible_ssh_pass }}"
      register: overlay_tzone

